# Generated by Django 4.1.2 on 2022-10-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="profile_pic",
            field=models.ImageField(
                default="profile_pics/default.jpeg", upload_to="profile_pics/"
            ),
        ),
    ]
